version: "3.8"

services:
  # Node.js 版本
  mineru-adapter-node:
    image: mineru-adapter:v1.1
    build: ./node
    container_name: mineru-adapter-node
    restart: always
    ports:
      - "3333:3333"
    environment:
      - MINERU_API_URL=https://xxxx/file_parse
      - MINERU_BACKEND=hybrid-auto-engine
      - PUBLIC_BASE_URL=http://127.0.0.1:3333/mineru_images
    volumes:
      - ./mineru_temp_images:/app/temp_images

  # Python 版本
  mineru-adapter-python:
    image: mineru-adapter-python:v1.0
    build: ./python
    container_name: mineru-adapter-python
    restart: always
    ports:
      - "3334:3333"
    environment:
      - MINERU_API_URL=https://xxxx/file_parse
      - MINERU_BACKEND=hybrid-auto-engine
      - PUBLIC_BASE_URL=http://127.0.0.1:3334/mineru_images
    volumes:
      - ./mineru_temp_images:/app/temp_images
